set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"
set -g repeat-time 200
set -sg escape-time 10

unbind C-b
set -g prefix M-Space
bind-key M-Space send-prefix
set -g status-right '%H:%M '
# Status bar, different styles list:
set -g status-style 'bg=#333333 fg=#5eacd3' # grey + decent blue
# set -g status-style 'bg=#333333 fg=#45d4ff' # grey + neon(y) blue

set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'clip.exe'
set-hook -g after-copy-mode "send -X start-of-line"

# vim-like pane switching
bind -r ^ last-window
# with tmux prefix (M-space, <>)
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
# merged with tmux prefix (M-<>)
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind -n M-h select-pane -L
bind -n M-l select-pane -R

set -g cursor-style block

# Allow tmux navigation with Alt-1,2,3,4,5,6,7,8,9,0 to select the window.
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 0
